# config file for automatic testing at travis-ci.org
language: python

python:
    - "3.4"
    - "2.7"

install:
    # update periodically - saves downloading if version is the same
    - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p "${HOME}/miniconda"
    - export PATH="${HOME}/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # useful for debugging any issues with conda
    - conda info -a

    # create a new conda env
    - conda create -q -n test-environment --file requirements/conda.txt python=$TRAVIS_PYTHON_VERSION pytest coverage numpy=1.9.2 bcolz=0.10 cython scipy PyYAML>=3.10 ipython pandas>=0.11.0 pyflakes pyzmq
    - source activate test-environment
    - conda install -c https://conda.anaconda.org/bcbio pysam pybedtools
    - pip install gemini

    # install dependencies
    - pip install -r requirements/dev.txt

    # install your own package + executables
    - pip install --editable .

    # pull HapMap database
    - wget https://s3-us-west-2.amazonaws.com/robinandeer/HapMapFew.db -O tests/fixtures/HapMapFew.db

script:
    # command to run tests and collect test coverage
    - py.test --flakes --cov-report html --cov puzzle tests/

notifications:
    email: false

after_success:
    coveralls
